app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://db-movies:5432/postgres   #project
      password: 'postgres'
      pool-size: 30
      username: postgres

server:
  error:
    include-binding-errors: always
    include-message: always

unleash:
  api-url: http://localhost:4242/api
  app-name: movies-app



