app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://db-movies:5432/postgres   #project
      password: 'postgres'
      pool-size: 30
      username: postgres

server:
  error:
    include-binding-errors: always
    include-message: always


feature:
  toggle:
    apiUrl: http://localhost:4242/api
    appName: movies
    clientSecret: "default:development.1ee5fb49a9f0f124853a2deee73a2da98d0ee36846ea400eff06e1fc"
    instanceId: "1"
    service: "unleash" # fakeFeatureFlag


